#cloud-config

coreos:
  flannel:
    etcd_endpoints: %(etcd_endpoint)s
    etcd_keyfile: %(certs_dir)s/node-key.pem
    etcd_certfile: %(certs_dir)s/node.pem
    etcd_cafile: %(certs_dir)s/ca.pem
    iface: $public_ipv4
  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            Environment=ETCD_SSL_DIR=%(certs_dir)s
            Environment=ETCDCTL_ENDPOINT=%(etcd_endpoint)s
            Environment=ETCDCTL_CA_FILE=%(certs_dir)s/ca.pem
            Environment=ETCDCTL_CERT_FILE=%(certs_dir)s/node.pem
            Environment=ETCDCTL_KEY_FILE=%(certs_dir)s/node-key.pem
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '%(network_config)s'
      command: start

write_files:
  - path: /etc/profile.d/10-etcdctl.sh
    permissions: 0644
    content: |
      export ETCDCTL_ENDPOINT=%(etcd_endpoint)s
      export ETCDCTL_CA_FILE=%(certs_dir)s/ca.pem
      export ETCDCTL_CERT_FILE=%(certs_dir)s/node.pem
      export ETCDCTL_KEY_FILE=%(certs_dir)s/node-key.pem
