#cloud-config

write_files:
  - path: /etc/profile.d/10-etcdctl.sh
    permissions: 0644
    content: |
      export ETCDCTL_ENDPOINT=%(etcd_endpoint)s
      export ETCDCTL_CA_FILE=/home/core/ca.pem
      export ETCDCTL_CERT_FILE=/home/core/node.pem
      export ETCDCTL_KEY_FILE=/home/core/node-key.pem
